[tox]
requires =
    tox>=4
env_list = py{310,311,312}
no_package = true

[testenv]
description = run apptrace unit tests
change_dir = apptrace
deps =
    --pre
    pytest-sugar
    -e {toxinidir}/apptrace[dev]
commands =
    pytest -vv tests/unit
