AZURE_ML_ENDPOINT_ENV_NAME = "AZUREML_ENTRY_SCRIPT"
AZURE_FUNCTION_WORKER_ENV_NAME = "FUNCTIONS_WORKER_RUNTIME"
AZURE_APP_SERVICE_ENV_NAME = "WEBSITE_SITE_NAME"

AZURE_FUNCTION_NAME = "azure_function"
AZURE_APP_SERVICE_NAME = "azure_app_service"
AZURE_ML_SERVICE_NAME = "azure_ml"
