"""Parametrized test cases are named after themselves, not their index.

A suite generated by setup_test_cases() is all one test function, so without this
every case reports as `test_x[testcase0]` and a failure says nothing about which
fact broke. The hook supplies the bracketed part of the node id; pytest already
prefixes the test function name.
"""
import pytest

from monocle_test_tools.pytest_plugin import pytest_make_parametrize_id
from monocle_test_tools.schema import FactID
from monocle_test_tools.testcase import FluentTestCase


def _id(val, argname="testcase"):
    return pytest_make_parametrize_id(config=None, val=val, argname=argname)


class TestFluentTestCaseValues:

    def test_uses_the_case_name(self):
        case = FluentTestCase(name="642dbd9d0dfcfdbdc8849f67f34c8a19")

        assert _id(case) == "642dbd9d0dfcfdbdc8849f67f34c8a19"

    def test_a_discovered_case_is_named_by_its_fact(self):
        case = FluentTestCase(name="aaa",
                              input=FactID(fact_id="aaa", source="okahu"))

        assert _id(case) == "aaa"

    def test_works_under_any_argname(self):
        """A FluentTestCase is unambiguous, so the argument name does not matter."""
        case = FluentTestCase(name="aaa")

        assert _id(case, argname="anything") == "aaa"

    def test_no_name_falls_back_to_pytest(self):
        assert _id(FluentTestCase(name=None)) is None


class TestDictValues:

    def test_uses_the_name_key_under_the_testcase_argname(self):
        assert _id({"name": "pinned-major", "evals": {"hallucination": "major"}}) == (
            "pinned-major")

    def test_ignored_under_another_argname(self):
        """Scoped to this feature's convention so unrelated dict params keep their ids."""
        assert _id({"name": "alice", "email": "a@example.com"}, argname="user") is None

    def test_dict_without_a_name_falls_back_to_pytest(self):
        assert _id({"evals": {"hallucination": "major"}}) is None

    def test_non_string_name_is_stringified(self):
        assert _id({"name": 7}) == "7"


class TestOtherValues:

    @pytest.mark.parametrize("val", ["a string", 42, None, ["a", "list"]])
    def test_unrelated_values_fall_back_to_pytest(self, val):
        assert _id(val) is None


def test_hook_is_wired_up(pytestconfig):
    """The plugin must actually expose the hook under its pytest name."""
    plugin = pytestconfig.pluginmanager.get_plugin("monocle_test_tools.pytest_plugin")
    assert plugin is None or hasattr(plugin, "pytest_make_parametrize_id")
